"""Add DailyIndexData table

Revision ID: f9cc24e0b0a8
Revises: 8bc053675ae3
Create Date: 2025-10-17 07:58:19.444787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cc24e0b0a8'
down_revision = '8bc053675ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_index_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jdate', sa.String(length=10), nullable=False),
    sa.Column('index_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jdate', 'index_type', name='uq_daily_index_data_jdate_type')
    )
    with op.batch_alter_table('daily_index_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_index_data_jdate'), ['jdate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_index_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_index_data_jdate'))

    op.drop_table('daily_index_data')
    # ### end Alembic commands ###
